# Generated by Django 3.0.2 on 2020-01-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
    ]
